omg bbq

diff --git a/.github/workflows/host-ci-main-postgres-release.yml b/.github/workflows/host-ci-main-postgres-release.yml
--- a/.github/workflows/host-ci-main-postgres-release.yml
+++ b/.github/workflows/host-ci-main-postgres-release.yml
@@ -24,7 +24,12 @@ jobs:
         run: dotnet restore ./odin-core.sln
 
       - name: Check for Vulnerable Packages
-        run: dotnet list ./odin-core.sln package --vulnerable --include-transitive || exit 1
+        run: |
+          dotnet list ./odin-core.sln package --vulnerable --include-transitive | tee packages_report.txt
+          if grep -q "vulnerable" packages_report.txt; then
+            echo "❌ Vulnerable packages detected! Failing the build."
+            exit 1
+          fi
 
       - name: Build
         # below: %3B is ASCII for semicolon
diff --git a/.github/workflows/host-ci-main-sqlite-release.yml b/.github/workflows/host-ci-main-sqlite-release.yml
--- a/.github/workflows/host-ci-main-sqlite-release.yml
+++ b/.github/workflows/host-ci-main-sqlite-release.yml
@@ -24,8 +24,13 @@ jobs:
         run: dotnet restore ./odin-core.sln
 
       - name: Check for Vulnerable Packages
-        run: dotnet list ./odin-core.sln package --vulnerable --include-transitive || exit 1
-
+        run: |
+          dotnet list ./odin-core.sln package --vulnerable --include-transitive | tee packages_report.txt
+          if grep -q "vulnerable" packages_report.txt; then
+            echo "❌ Vulnerable packages detected! Failing the build."
+            exit 1
+          fi
+      
       - name: Build
         # below: %3B is ASCII for semicolon
         run: dotnet build --no-restore --configuration Release --warnaserror --property:DefineConstants="CI_GITHUB%3BCI_LINUX" ./odin-core.sln
