github action: only allow main

diff --git a/.github/workflows/host-build-and-deploy-branch-to-environment.yml b/.github/workflows/host-build-and-deploy-branch-to-environment.yml
--- a/.github/workflows/host-build-and-deploy-branch-to-environment.yml
+++ b/.github/workflows/host-build-and-deploy-branch-to-environment.yml
@@ -46,6 +46,12 @@ jobs:
         with:
           path: odin-core
 
+      - name: Only allow main branch
+        if: github.ref != 'refs/heads/main'
+        run: |
+          echo "Error: Workflow must run on 'main' branch. Current ref: ${{ github.ref }}"
+          exit 1          
+
       #
       # Build Frontend
       #
diff --git a/.github/workflows/host-create-new-release-from-tip-of-branch.yml b/.github/workflows/host-create-new-release-from-tip-of-branch.yml
--- a/.github/workflows/host-create-new-release-from-tip-of-branch.yml
+++ b/.github/workflows/host-create-new-release-from-tip-of-branch.yml
@@ -20,6 +20,12 @@ jobs:
           fetch-depth: 0 # Fetch all history so we can see all tags
           path: odin-core
 
+      - name: Only allow main branch
+        if: github.ref != 'refs/heads/main'
+        run: |
+          echo "Error: Workflow must run on 'main' branch. Current ref: ${{ github.ref }}"
+          exit 1          
+
       - name: Execute versioning script
         working-directory: odin-core
         run: |
