more checking

diff --git a/.github/workflows/host-deploy-latest-release-to-production.yml b/.github/workflows/host-deploy-latest-release-to-production.yml
--- a/.github/workflows/host-deploy-latest-release-to-production.yml
+++ b/.github/workflows/host-deploy-latest-release-to-production.yml
@@ -21,6 +21,12 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Only allow main branch
+        if: github.ref != 'refs/heads/main'
+        run: |
+          echo "Error: Workflow must run on 'main' branch. Current ref: ${{ github.ref }}"
+          exit 1          
+
       - name: Checkout Repository
         uses: actions/checkout@v4 
 
