hop

diff --git a/.github/workflows/sebs-sandbox-deploy.yml b/.github/workflows/sebs-sandbox-deploy.yml
--- a/.github/workflows/sebs-sandbox-deploy.yml
+++ b/.github/workflows/sebs-sandbox-deploy.yml
@@ -29,7 +29,12 @@ jobs:
         run: dotnet restore ./odin-core.sln
 
       - name: Check for Vulnerable Packages
-        run: dotnet list ./odin-core.sln package --vulnerable --include-transitive || exit 1
+        run: |
+          dotnet list ./odin-core.sln package --vulnerable --include-transitive | tee packages_report.txt
+          if grep -q "Severity" packages_report.txt; then
+            echo "❌ Vulnerable packages detected! Failing the build."
+            exit 1
+          fi
 
       - name: Build
         run: dotnet build --no-restore --configuration Debug --warnaserror ./odin-core.sln
